site_name: gotran-parser
site_description: Parser for gotran ode files
strict: true

theme:
  name: "material"
repo_name: finsberg/gotran-parser
repo_url: https://github.com/finsberg/gotran-parser


nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Demos: "demos.md"
  - Contributing: "contributing.md"

markdown_extensions:
  - admonition  #  note blocks, warning blocks -- https://github.com/mkdocs/mkdocs/issues/1659

plugins:
- search
